## NUMPY OPERATIONS

### Arithmetic Operations
You can perform array on array, and scalar on array operations with ease with numpy

In [2]:
import numpy as np

In [4]:
arr = np.arange(0, 8)

arr # show

array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
arr + arr # addition

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [6]:
arr - arr # subtraction

array([0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
arr * arr # multiplication

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [8]:
# zero by division warning (not error) will occur - so because answer is replaced with nan
arr / arr # division

C:\Users\Dell\AppData\Local\Temp\ipykernel_2944\3765936669.py:2: RuntimeWarning: invalid value encountered in divide
  arr / arr # division


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [9]:
# here 0 is replaced with inf(infinity) instead of nan
1 / arr # another division anomaly

C:\Users\Dell\AppData\Local\Temp\ipykernel_2944\402844737.py:2: RuntimeWarning: divide by zero encountered in divide
  1 / arr # another division anomaly


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714])

In [10]:
arr + 5 # addition with a scalar

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
arr - 5 # subtraction with a scalar

array([-5, -4, -3, -2, -1,  0,  1,  2])

In [12]:
arr ** 2 # square...

# and so on

array([ 0,  1,  4,  9, 16, 25, 36, 49])

## Universal Array Functions
Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array.

In [14]:
_arr = np.arange(0, 11)

_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.sqrt(_arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [18]:
np.exp(_arr) # exp e^

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [19]:
np.max(_arr) # max of _arr

10

In [21]:
np.min(_arr) # assuming min

0

In [22]:
np.sin(_arr) # sin

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [23]:
np.cos(_arr) # cos

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [25]:
# zero gets replaced by -inf
np.log(_arr) # another division by zero scenario.

C:\Users\Dell\AppData\Local\Temp\ipykernel_2944\3424829162.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(_arr) # another division by zero scenario.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])