# NumPy Arrays

### CREATING NUMPY ARRAYS
* From a python list 
* Built-in methods





#### FROM A PYTHON LIST

In [2]:
lst = [1, 2, 3, 4, 5]

In [3]:
import numpy as np

In [8]:
arr = np.array(lst)
arr

array([1, 2, 3, 4, 5])

In [9]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### BUILT-IN METHODS

##### arange
returns evenly spaced values a given interval

In [11]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(0, 50, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

##### zeroes and ones
generates arrays of zeroes and ones

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.ones((5, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

##### linspace
returns evenly spaced numbers over a specified interval

In [23]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [24]:
np.linspace(12, 36, 20)

array([12.        , 13.26315789, 14.52631579, 15.78947368, 17.05263158,
       18.31578947, 19.57894737, 20.84210526, 22.10526316, 23.36842105,
       24.63157895, 25.89473684, 27.15789474, 28.42105263, 29.68421053,
       30.94736842, 32.21052632, 33.47368421, 34.73684211, 36.        ])

##### eye
Creates an identity matrix

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### RANDOM
NumPy has a lot of ways to create random number arrays

##### rand

creates an array of a given shape and populates it with random samples from a uniform distribution over [0, 1].

In [37]:
np.random.rand(5)

array([0.6976016 , 0.51279284, 0.40151011, 0.7947723 , 0.30563405])

In [38]:
np.random.rand(3, 3)

array([[0.03733285, 0.15919347, 0.38630106],
       [0.4038193 , 0.1726098 , 0.46855847],
       [0.77837495, 0.97748974, 0.0174067 ]])

##### randn
creates an array of a given shape and populates it with random samples from a standard normal distribution. Unlike rand which is uniform

In [39]:
np.random.randn(5)

array([-1.06091494, -0.97138095,  0.72058077,  0.58518872,  0.29599852])

In [40]:
np.random.randn(4, 4)

array([[ 0.8543403 , -0.19039587, -1.19075851, -1.04122205],
       [ 1.00208413,  1.10716731, -0.13511923,  2.77961079],
       [ 0.3182677 ,  0.08782461,  1.01718286, -0.32493609],
       [-1.53379438, -0.06296197, -0.64920792, -0.01948953]])

##### randint
creates an array of random integers from low(inclusive) to high(exclusive)

In [41]:
np.random.randint(1, 10)

7

In [42]:
# third argument is the number of items in an array
np.random.randint(1, 10, 5)

array([3, 5, 8, 5, 6])

In [44]:
np.random.randint(5, 20, 15)

array([15, 10,  9, 18, 16, 17, 17, 18, 12, 18,  8, 17, 13, 14,  6])

### Array Attributes and Methods
Useful attributes and methods of an array

In [49]:
arr = np.arange(25)
randarr = np.random.randint(12, 36, 15)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
randarr

array([34, 12, 13, 20, 29, 16, 13, 35, 27, 16, 23, 16, 26, 19, 26])

#### Reshape
Returns an array of the same data but of different dimension (shape)

In [53]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
randarr.reshape(5, 3)

array([[34, 12, 13],
       [20, 29, 16],
       [13, 35, 27],
       [16, 23, 16],
       [26, 19, 26]])

#### min, max, argmin, argmax
These are methods to find the min and maximum values of an array and their indexes

In [60]:
randarr.max() # maximum value of randarr

35

In [61]:
randarr.argmax() # index of the maximum value

7

In [62]:
randarr.min() # min value of randarr

12

In [63]:
randarr.argmin() # index of the minimum value

1

#### Shape 
Shape is an attribute that arrays have

In [64]:
arr.shape # vector

(25,)

In [65]:
randarr.shape # vector

(15,)

In [66]:
randarr.reshape(1, 15) # Pay attention to the two brackets in the output

array([[34, 12, 13, 20, 29, 16, 13, 35, 27, 16, 23, 16, 26, 19, 26]])

In [68]:
randarr.reshape(1, 15).shape

(1, 15)

In [69]:
randarr.reshape(15, 1) # Notice the difference ???

array([[34],
       [12],
       [13],
       [20],
       [29],
       [16],
       [13],
       [35],
       [27],
       [16],
       [23],
       [16],
       [26],
       [19],
       [26]])

In [70]:
randarr.reshape(15, 1).shape

(15, 1)

#### dtype
Tells the datatype of the content of an array

In [71]:
arr.dtype

dtype('int32')

In [72]:
randarr.dtype

dtype('int32')