## NUMPY INDEXING AND SELECTION

How to basically grab elements from a numpy array

In [1]:
import numpy as np

In [4]:
arr = np.arange(15) # create an array

In [5]:
arr # display

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Bracket Indexing and Selection
Similar to what we have in python lists

In [6]:
arr[5]

5

In [9]:
arr[8:11]

array([ 8,  9, 10])

In [14]:
arr[:4]

array([0, 1, 2, 3])

In [15]:
arr[12:]

array([12, 13, 14])

### Broadcasting
One difference between numpy arrays and lists is that values can be broadcast through them. 

In [16]:
# populating the first 5 items in arr with 50
arr[0:5] = 50

arr

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
# Reseting arr 
arr = np.arange(0, 11)

arr # show

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# Pay attention to what is about to happen below

In [20]:
# creating a slice of arr
slice_of_arr = arr[7:]

slice_of_arr[:] = 77 # broadcasting entire slice with 77

slice_of_arr

array([77, 77, 77, 77])

In [21]:
# Notice the output after running this cell

arr

array([ 0,  1,  2,  3,  4,  5,  6, 77, 77, 77, 77])

Broadcasting the slice seems to have affected the original array

Data is not copied. It's a view of the original array. This prevents memory issues.

In [22]:
# To fix this, explicitly make a copy of the array
arr_copy = arr.copy()

arr_copy

array([ 0,  1,  2,  3,  4,  5,  6, 77, 77, 77, 77])

In [25]:
slice_of_arr_copy = arr_copy[7:]

slice_of_arr_copy

array([77, 77, 77, 77])

In [26]:
slice_of_arr_copy[:] = 99

slice_of_arr_copy

array([99, 99, 99, 99])

In [27]:
arr_copy # copy changes

array([ 0,  1,  2,  3,  4,  5,  6, 99, 99, 99, 99])

In [28]:
arr # original remains intact

array([ 0,  1,  2,  3,  4,  5,  6, 77, 77, 77, 77])

### Indexing of 2D Array(matrices)
General format is _2D[row][col] or _2D[row, col] (recommended)

In [29]:
_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

_2D # show

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
_2D[2] # accessing row at index 2

array([7, 8, 9])

In [31]:
_2D[2][0] # column index 0 of row index 2

7

In [32]:
_2D[2, 0] # alternative ( recommended )

7

In [34]:
## 2D array slicing

_2D[:, 1:] # shape (2, 3)

array([[2, 3],
       [5, 6],
       [8, 9]])

In [35]:
# Shape of bottom row
_2D[2]

array([7, 8, 9])

In [36]:
# OR shape of bottom row
_2D[2, :]

array([7, 8, 9])

### Fancy Indexing
Allows you to select entire rows or columns out of order. 

In [42]:
__2D = np.zeros((10, 5))

__2D # show

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
# Length of array
length_of_array = __2D.shape[0]

In [47]:
# setup content of __2D

for row in range(length_of_array):
    __2D[row] = row

__2D # show

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9.]])

Fancy indexing allows you to grap entire rows like this

In [48]:
__2D[[0, 5, 8]]

array([[0., 0., 0., 0., 0.],
       [5., 5., 5., 5., 5.],
       [8., 8., 8., 8., 8.]])

In [50]:
__2D[[6, 3, 9, 1]] # allows in any order

array([[6., 6., 6., 6., 6.],
       [3., 3., 3., 3., 3.],
       [9., 9., 9., 9., 9.],
       [1., 1., 1., 1., 1.]])

### SELECTION
How to use brackets for selection using comparison operators

In [57]:
arr = np.arange(0, 30, 3) 

arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [58]:
arr > 3

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [61]:
bool_arr = arr > 5

arr[bool_arr]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [62]:
arr[arr>5]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [63]:
x = 15

arr[arr<x]

array([ 0,  3,  6,  9, 12])